### ISSUE TITLE
Not using CMake target_sources?

### ISSUE THREAD

**Issue by matt-chan** [GQCG/cpputil#34]
I saw that #13 removed the globbing to get sources, but I'm not sure why we don't use `target_sources`?

https://crascit.com/2016/01/31/enhanced-source-file-handling-with-target_sources/

It helps keep things a little more sane to use them I think. Your CMakeLists.txt within each src directory can add them, and you can move your `add_library` or `add_executable` calls to the top level CMakeLists.txt.

I can make a PR for this in a few days if it's something you guys are interested in.

**Comment by lelemmen** [comment]
@matt-chan Yes, sure! I'd like to see the differences.

**Comment by matt-chan** [comment]
Sorry I got caught up with some other HORTON stuff!

I'll make it after you guys merge in the shared library changes!

**Comment by lelemmen** [comment]
I'm bringing over this issue to the gqcp library.
